using System;
using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;
using static WorldObject_Classes;

public class CollectableGenerator : MonoBehaviour
{
    // Grab Enemy Prefabs
    private List<GameObject> collectableList = new List<GameObject>();
    private List<Vector3> collectableSpawnPositions = new List<Vector3>();

    // Grab Spawn Positions 
    private UnityEngine.Object[] initArrayOfEnemySpawnMarkers;
    private Transform parentObj;
    private GameObject collectableObj;
    private Transform collectableToSpawn;

    private ProceduralAI ai;

    // Start is called before the first frame update
    void Awake()
    {
        // Fetch list of Platform prefabs (Runs in Start to ensure list has been generated by other script on Awake)
        collectableList = ProceduralAI.collectablePrefabs;
        try
        {
            collectableSpawnPositions = GenerateCollectableSpawnMarkerPositions();

        }
        catch (NullReferenceException nre)
        {
            Debug.Log(nre.Message);
        }
    }

    // Update is called once per frame
    void Update()
    {

    }
    #region Spawner
    public void SpawnCollectables()
    {
        parentObj = gameObject.transform;

        foreach (Transform childObj in parentObj)
        {
            if (childObj.CompareTag("CollectableSpawn"))
            {
                collectableSpawnPositions.Add(childObj.position);
            }
        }
        //Get the transform to refrence the Spawn Positions
        //Transform spawnedEnemy = SpawnEnemies(enemySpawnPositions);
        foreach (Vector3 enemySpawnPosition in collectableSpawnPositions)
        {
            SpawnCollectables(enemySpawnPosition);
        }
    }

    // SpawnEnemies(AtPosition)
    public Transform SpawnCollectables(Vector3 enemySpawnPosition)
    {
        // Get random Enemy from List
        collectableToSpawn = RandomCollectableGenerator(0, collectableList.Count);
        //Vector3 spawnPoint = RandomSpawnGenerator(0, enemySpawnPositions.Count);
        Transform spawnEnemy = Instantiate(collectableToSpawn, enemySpawnPosition, Quaternion.identity);
        ProceduralAI.enemySpawned += 1;
        // Return the transform for sister method
        return spawnEnemy;
    }
    #endregion

    // REGGIE
    private Transform RandomCollectableGenerator(int floor, int ceiling)
    {
        // Variable to hold the index of random list element
        int randomCollectable = 0;

        // Get random index for list
        randomCollectable = UnityEngine.Random.Range(0, collectableList.Count);

        // Call GameObject from list and get its transform
        collectableObj = collectableList[randomCollectable];
        collectableToSpawn = collectableObj.transform;

        // Return the randomly-chosen enemy to spawn
        return collectableToSpawn;
    }

    private Vector3 RandomSpawnGenerator(int floor, int ceiling)
    {
        // Variable to hold the index of random list element
        int randomSpawnPoint = 0;

        // Get random index for list
        randomSpawnPoint = UnityEngine.Random.Range(0, collectableSpawnPositions.Count);

        // Call Vector from list and get its transform
        Vector3 spawnPoint = collectableSpawnPositions[randomSpawnPoint];
        //enemyToSpawn = enemyObj.transform;

        // Return the randomly-chosen enemy to spawn
        return spawnPoint;
    }

    public List<Vector3> GenerateCollectableSpawnMarkerPositions()
    {
        if (collectableSpawnPositions.Count > 0)
        {
            collectableSpawnPositions.Clear();

            try
            {
                parentObj = gameObject.transform;

                foreach (Transform childObj in parentObj)
                {
                    if (childObj.CompareTag("EnemySpawn"))
                    {
                        collectableSpawnPositions.Add(childObj.position);
                    }
                }
            }
            catch (NullReferenceException nre)
            {
                Debug.Log("Null Reference Exception! : " + nre);
            }

            return new List<Vector3>(collectableSpawnPositions);
        }
        else
        {
            try
            {
                parentObj = gameObject.transform;

                foreach (Transform childObj in parentObj)
                {
                    if (childObj.CompareTag("EnemySpawn"))
                    {
                        collectableSpawnPositions.Add(childObj.position);
                    }
                }
            }
            catch (NullReferenceException nre)
            {
                Debug.Log("Null Reference Exception! : " + nre);
            }

            // Return new Enemy List
            return new List<Vector3>(collectableSpawnPositions);
        }
    }

    private void OnDisable()
    {
        // Code here
    }



}
