using System;
using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;
using static WorldObject_Classes;

public class EnemyGenerator : MonoBehaviour
{
    // Grab Enemy Prefabs
    private List<GameObject> enemyList = new List<GameObject>();
    private List<Vector3> enemySpawnPositions = new List<Vector3>();

    // Grab Spawn Positions 
    private UnityEngine.Object[] initArrayOfEnemySpawnMarkers;
    private Transform parentObj;
    private GameObject enemyObj;
    private Transform enemyToSpawn;

    private ProceduralAI ai;

    // Start is called before the first frame update
    void Awake()
    {
        // Fetch list of Platform prefabs (Runs in Start to ensure list has been generated by other script on Awake)
        enemyList = ProceduralAI.trapPrefabs;
        try
        {
            enemySpawnPositions = GenerateEnemySpawnMarkerPositions();

        }
        catch (NullReferenceException nre)
        {
            Debug.Log(nre.Message);
        }
    }

    // Update is called once per frame
    void Update()
    {
        
    }
    #region Spawner
    public void SpawnEnemies()
    {
        parentObj = gameObject.transform;

        foreach (Transform childObj in parentObj)
        {
            if (childObj.CompareTag("EnemySpawn"))
            {
                enemySpawnPositions.Add(childObj.position);         
            }
        }
        //Get the transform to refrence the Spawn Positions
        //Transform spawnedEnemy = SpawnEnemies(enemySpawnPositions);
        foreach (Vector3 enemySpawnPosition in enemySpawnPositions)
        {
            SpawnEnemies(enemySpawnPosition);
        }
    }

    // SpawnEnemies(AtPosition)
    public Transform SpawnEnemies(Vector3 enemySpawnPosition)
    {
        // Get random Enemy from List
        enemyToSpawn = RandomEnemyGenerator(0, enemyList.Count);

        // Get the Transform to Spawn Instance and log to controller + console
        Transform spawnEnemy = Instantiate(enemyToSpawn, enemySpawnPosition, Quaternion.identity);
        ProceduralAI.enemySpawned += 1;
        Debug.Log("Enemy Spawned: " + spawnEnemy.name + ". Total Enemies spawned: " + ProceduralAI.enemySpawned);

        // Return enemy transform
        return spawnEnemy;    
    }
#endregion

    // REGGIE
    private Transform RandomEnemyGenerator(int floor, int ceiling)
    {
        // Variable to hold the index of random list element
        int randomEnemy = 0;

        try
        {
            // Get random index for list
            randomEnemy = UnityEngine.Random.Range(floor, ceiling);

            // Call GameObject from list and get its transform
            enemyObj = enemyList[randomEnemy];
            enemyToSpawn = enemyObj.transform;

            // Return the randomly-chosen enemy to spawn
            return enemyToSpawn;
        }
        catch (ArgumentException ae)
        {
            Debug.Log(ae.Message);

            if (enemyList.Count == 0 )
            {
                // Generate new Marker list
                enemyList = ai.GenerateEnemyList();
            }

            // Get random index for list
            randomEnemy = UnityEngine.Random.Range(floor, ceiling);

            // Call GameObject from list and get its transform
            enemyObj = enemyList[randomEnemy];
            enemyToSpawn = enemyObj.transform;

            // Return the randomly-chosen enemy to spawn
            return enemyToSpawn;
        }
    }

    private Vector3 RandomSpawnGenerator(int floor, int ceiling)
    {
        // Variable to hold the index of random list element
        int randomSpawnPoint = 0;

        // Get random index for list
        randomSpawnPoint = UnityEngine.Random.Range(floor, ceiling);

        // Call Vector from list and get its transform
        Vector3 spawnPoint = enemySpawnPositions[randomSpawnPoint];
        //enemyToSpawn = enemyObj.transform;

        // Return the randomly-chosen enemy to spawn
        return spawnPoint;
    }

    public List<Vector3> GenerateEnemySpawnMarkerPositions()
    {
        if (enemySpawnPositions.Count > 0)
        {
            enemySpawnPositions.Clear();

            try
            {
                parentObj = gameObject.transform;

                foreach (Transform childObj in parentObj)
                {
                    if (childObj.CompareTag("EnemySpawn"))
                    {
                        enemySpawnPositions.Add(childObj.position);
                    }
                }
            }
            catch (NullReferenceException nre)
            {
                Debug.Log("Null Reference Exception! : " + nre);
            }

            return new List<Vector3>(enemySpawnPositions);
        }
        else
        {
            try
            {
                parentObj = gameObject.transform;

                foreach (Transform childObj in parentObj)
                {
                    if (childObj.CompareTag("EnemySpawn"))
                    {
                        enemySpawnPositions.Add(childObj.position);
                    }
                }
            }
            catch (NullReferenceException nre)
            {
                Debug.Log("Null Reference Exception! : " + nre);
            }

            // Return new Enemy List
            return new List<Vector3>(enemySpawnPositions);
        }
    }

    private void OnDisable()
    {
        // Code here
    }



}
