using System;
using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;
using static WorldObject_Classes;

public class EnemyGenerator : MonoBehaviour
{
    // Grab Enemy Prefabs
    private static List<GameObject> enemyList = new List<GameObject>();
    private static List<GameObject> enemySpawnMarkers = new List<GameObject>();

    // Grab Spawn Positions 
    private UnityEngine.Object[] initArrayOfEnemySpawnMarkers;
    private static List<Vector3> enemySpawnPositions = new List<Vector3>();
    private GameObject enemyObj;
    private Transform enemyToSpawn;
    private ProceduralAI ai;

    // Start is called before the first frame update
    void Awake()
    {
        // Fetch list of Platform prefabs (Runs in Start to ensure list has been generated by other script on Awake)
        enemyList = ProceduralAI.enemyPrefabs;
        enemySpawnMarkers = GenerateEnemySpawnMarkerList();

    }

    // Update is called once per frame
    void Update()
    {
        
    }
    #region Spawner
    public void SpawnEnemies()
    {
        foreach (Transform transform in gameObject.transform)
        {
            if (transform.CompareTag("EnemySpawn"))
            {
                enemySpawnPositions.Add(transform.position);
                break;
            }
        }

        //Get the transform to refrence the Spawn Positions
        Transform spawnedEnemy = SpawnEnemies(enemySpawnPositions);
        
        
        //enemyToSpawn = RandomEnemyGenerator(0, enemyList.Count);
    }

    // SpawnEnemies(AtPosition)
    public Transform SpawnEnemies(List<Vector3> enemySpawnPositions)
    {
        // Get random Enemy from List
        enemyToSpawn = RandomEnemyGenerator(0, enemyList.Count);

        foreach (Vector3 enemySpawnPosition in enemySpawnPositions)
        {
            Transform enemy = Instantiate(enemyToSpawn, enemySpawnPosition, Quaternion.identity);
            ProceduralAI.enemySpawned += 1;
        }

        // Return the transform for sister method
        return enemyToSpawn;
    }
#endregion

    // REGGIE
    private Transform RandomEnemyGenerator(int floor, int ceiling)
    {
        // Variable to hold the index of random list element
        int randomEnemy = 0;

        // Get random index for list
        randomEnemy = UnityEngine.Random.Range(0, enemyList.Count);

        // Call GameObject from list and get its transform
        enemyObj = enemyList[randomEnemy];
        enemyToSpawn = enemyObj.transform;

        // Return the randomly-chosen enemy to spawn
        return enemyToSpawn;
    }

    public List<GameObject> GenerateEnemySpawnMarkerList()
    {
        try
        {
            enemySpawnMarkers = ai.GenerateEnemySpawnMarkerList();
        }
        catch (NullReferenceException nre)
        {
            Debug.Log("Null Reference Exception! : " + nre);
        }
        finally
        {
            //enemySpawnMarkers = enemySpawnMarkers.Clear();
        }
        
        // Return new Enemy List
        return new List<GameObject>(enemySpawnMarkers);
    }

    private void OnDisable()
    {
        // Code here
    }



}
