using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TrapGenerator : MonoBehaviour
{
    private static List<GameObject> trapList = new List<GameObject>();
    private GameObject trapObj;
    private Transform trapToSpawn;
    
    // Start is called before the first frame update
    void Start()
    {
        // Fetch list of Platform prefabs (Runs in Start to ensure list has been generated by other script on Awake)
        trapList = ProceduralAI.trapPrefabs;
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    private Transform RandomTrapGenerator(int floor, int ceiling)
    {
        // Variable to hold the index of random list element
        int randomTrap = 0;

        // Get random index for list
        randomTrap = UnityEngine.Random.Range(0, trapList.Count);

        // Call GameObject from list and get its transform
        trapObj = trapList[randomTrap];
        trapToSpawn = trapObj.transform;

        // Return the randomly-chosen Platform Chunk
        return trapToSpawn;
    }


}
